name: CI Frontend

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Traer el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        run: npm run lint

      # Cuando haya tests, descomentar las siguientes dos líneas:
      # - name: Ejecutar Tests
      #   run: npm run test

      - name: Construir el proyecto (Build)
        run: npm run build